version: "3.9"
services:
  app:
    build: 
      context: .
      args:
        - CONTAINER_WORKDIR=${CONTAINER_WORKDIR}
        - CONTAINER_CRON_D_DIR=${CONTAINER_CRON_D_DIR}
    env_file:
      - .env
    volumes:
      - ${PWD}:${CONTAINER_WORKDIR}
      - ${LOCAL_LOGSEQ_DIR}:${CONTAINER_LOGSEQ_DIR}
